### ISSUE TITLE
network id underflow

### ISSUE THREAD

**Issue by Quezler** [nihilistzsche/Factorio-LtnManager#170]
#### Describe the Bug

The trains & depot tabs show -1 as the network id, but on history & alerts it underflows to an unsigned integer:

![Screen Shot 2021-12-30 at 16 14 35](https://user-images.githubusercontent.com/3179271/147764275-3abb2e65-e5ac-40ea-b2f6-f2e6baa18b6e.png)
![Screen Shot 2021-12-30 at 16 14 46](https://user-images.githubusercontent.com/3179271/147764279-9b9e9d5d-152e-47cd-9d71-ae996a46e7bb.png)
![Screen Shot 2021-12-30 at 16 14 57](https://user-images.githubusercontent.com/3179271/147764281-23738133-f08d-4290-a3ac-aa38a07ece83.png)
![Screen Shot 2021-12-30 at 16 15 04](https://user-images.githubusercontent.com/3179271/147764284-d3d926f4-d7a7-4249-a972-901ecff3bd0d.png)

#### To Reproduce

1. have some trains running to fill those tabs
2. click between them and compare

#### Save file & Username

[`Quezler`](http://83.137.145.42/ltn-manager-underflow.zip)

#### Log file

I'd rather not post that publicly since it contains ips and whatnot, please ping me (`@Quezler#3982`) on the factorio discord if you want it in your dm's.

**Comment by raiguard** [comment]
My PC will not download your file due to "security risks". Could you upload it to a file sharing site (i.e. Google Drive or Dropbox)?

**Comment by Quezler** [comment]
Unfortunately i don't have either of those on hand (not logged in), mind if i try sending it via a discord dm?

**Comment by raiguard** [comment]
It's alright, I managed to reproduce it independently.

Unfortunately, this appears to be in LTN itself, LTN Manager is displaying exactly what it is getting. I'm going to reach out to Optera about this.

**Comment by Yousei9** [comment]
What part of the LTN API would send unsigned int for it to appear like that in your history?

**Comment by raiguard** [comment]
You were right @Yousei9, it isn't LTN's fault. I'm copying the network ID from the train entry to the history, by doing `entry.network_id = train.network_id`, and it's changing it from unsigned to signed. Very odd.
